title: Elizabeth's Website
description: > # this means to ignore newlines until "baseurl:"
 Elizabeth Childs is a PhD Candidate at Stanford University investigating augmented reality for education.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://liberty293.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Elizabeth Childs # add your name
author-img: elizabeth-childs.png # add your photo
about-author: "Bachelors of Science in Mechanical Engineering at the University of Maryland, College Park <br><br> Stanford University PhD Candidate <br><br> PhD topic:Augmented Reality for Science Education <br><br> Advisors: James Landay and Allison Okamura <br>"
# add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: liberty293 # add your Github handle
social-linkedin: ehchilds # add your Linkedin handle
social-email: elchilds@stanford.edu # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
